language: node_js
node_js: stable

# S: Build Lifecycle
before_install:
 - npm install -g yarn

install:
  - yarn install

script:
  - yarn dev

after_script:
  - cd ./dist
  - git init
  - git config user.name "NoManReady"
  - git config user.email "453421041@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/NoManReady/NoManReady.github.io.git